properNouns: tuple[str, ...] = (
    "Ada Lovelace",
    "Agatha Christie",
    "Albert Camus",
    "Albert Einstein",
    "Alexander Graham Bell",
    "Balthazar McSnazz",
    "Barack Obama",
    "Baron Von Snoodle",
    "Bill Gates",
    "Charles Darwin",
    "Charles Dickens",
    "Charlotte Brontë",
    "Claude Monet",
    "David Beckham",
    "Donald Duck",
    "Donald Trump",
    "Edgar Allan Poe",
    "Elon Musk",
    "Emily Brontë",
    "Ernest Hemingway",
    "Fake unknown",
    "Frida Kahlo",
    "Fyodor Dostoevsky",
    "Galileo Galilei",
    "George Orwell",
    "Grumpy Cat",
    "Harper Lee",
    "He Who Must Be Obeyed",
    "He Who Shall Not Be Named",
    "Isaac Newton",
    "J.K. Rowling",
    "J.R.R. Tolkien",
    "Jane Austen",
    "Joe Biden",
    "Johannes Vermeer",
    "Kanye West",
    "Leo Tolstoy",
    "Leonardo DiCaprio",
    "Leonardo da Vinci",
    "Lord McSassypants",
    "Mahatma Gandhi",
    "Malala Yousafzai",
    "Marie Curie",
    "Mark Twain",
    "Michelangelo",
    "Nelson Mandela",
    "Ninja",
    "Oprah Winfrey",
    "Pablo Picasso",
    "Pierre-Auguste Reno",
    "Probably Sharts",
    "Proton Bomb",
    "Stephen King",
    "Steve Jobs",
    "Taylor Swift",
    "The Duke of Disco",
    "The Earl of Eccentric",
    "The Great Sock Eater",
    "The Incredible Sulk",
    "The King Kookiness",
    "The Marquis Mischief",
    "The Mysterious Donut",
    "The Viscount Vexation",
    "Thomas Edison",
    "Toni Morrison",
    "Vincent Van Gogh",
    "Virginia Woolf",
    "William Shakespeare",
    "Zorgon Destroyer",
)
